name: OWASP ZAP daily scan

on:
  pull_request:
    branches: [main]
  # schedule:
  #   # cron format: 'minute hour dayofmonth month dayofweek'
  #   # this will run at noon UTC every day (7am EST / 8am EDT)
  #   - cron: '0 12 * * *'

jobs:
  owasp-scan:
    name: OWASP ZAP Scan
    runs-on: ubuntu-latest
    permissions:
      issues: write
    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: iv_cbv_payroll_test
          POSTGRES_USER: cidbuser
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v4

      - id: setup
        uses: ./.github/actions/setup-project
        with:
          rails_env: test

      - uses: ./.github/actions/run-server
        with:
          database_url: ${{ steps.setup.outputs.database_url }}

      - name: Run OWASP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'http://localhost:3000/'
          fail_action: true
          cmd_options: -c app/zap.conf -z "-configfile /zap/wrk/zap_options.conf"
